chore(ui): add folder filled icon for storage table
wandb/weave pull request #1234
Opened 2024-02-21 00:37 UTC by ericakdiaz

This adds the folder-filled icon that will be used in the new Storage Explorer

2024-02-21 00:38 UTC, ericakdiaz commented
I have read the CLA Document and I hereby sign the CLA

2024-02-21 00:42 UTC, jamie-rasmussen requested changes
Hello! Would you mind asking the designer who provided this icon to re-export it at 24x24 and add it to the Google drive folder?

2024-02-29 21:11 UTC, ericakdiaz commented
Hi @jamie-rasmussen, the icon has been added to the Google Drive at 24 x 24, and I've updated the file here as well :)

2024-02-29 21:43 UTC, jamie-rasmussen approved these changes

2024-02-29 21:48 UTC, merged