feat(integration): add CrewAI integration
wandb/weave pull request #1743
Opened 2024-06-10 13:47 UTC by ayulockin

This PR auto-patches the key methods of `Crew`, `Agent` and `Task` classes. These three classes together form an Agentic pipeline.

This PR utilises #1661 to trace underlying Langchain chains and LLM calls.

2024-06-11 11:00 UTC, ayulockin commented
I have read the CLA Document and I hereby sign the CLA

2024-06-14 22:32 UTC, tssweeney commented on weave/integrations/crewai/crewai_sdk.py
> +        make_new_value=weave.op(),
we should use namespaced names `crewai.` in front of everything. see https://github.com/wandb/weave/pull/1632 for example

2024-06-14 22:32 UTC, tssweeney commented on weave/integrations/crewai/crewai_test.py
> +    assert calls[0].inputs["messages"][0]["role"] == "user"
are there any other assertions you would like to include here to ensure that things were tracked correctly?

2024-06-14 22:33 UTC, tssweeney commented on weave/integrations/crewai/cassettes/crewai_test/test_simple_crew.yaml
> +- request:
This entire first block targeting `https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json` can be removed, dramatically reducing this file size

2024-06-14 22:34 UTC, tssweeney requested changes
Changes requested:
* Trim Cassette
* Add name prefixes
* Add some more test assertions

2025-03-06 11:12 UTC, ayulockin commented
Closing this in favour of #3678.

2025-03-06 11:12 UTC, closed without merging