feat(Cohere)
wandb/weave pull request #1846
Opened 2024-06-26 09:56 UTC by tcapelle

Cohere API integration with Weave

2024-06-26 10:36 UTC, tcapelle commented
@tssweeney I need help with 2 things:
- the output of the cohere SDK is a `pydantic.v1.BaseModel` that we don't parse correctly
- I think the wrapped function in cohere SDK patches after the weave patch, and that's why the name is ignored. For the streaming version the naming is correctly displayed, I suppose the accumulator fixes the naming.

2024-07-05 14:18 UTC, tcapelle commented
The only thing that may need changing is how the patching is applied.

As you know @tssweeney the cohere Client modifies the chat function on the init, so we need to patch before creating a client. Two options for this:
- We call `weave.init` before creating the client (this is weird in general and wouldn't be how most of of the users do, but... it is all over our docs: anthropic, mistral, etc...)
- We manually patch before creating a client. Something closer to where the imports happen.

2024-07-05 18:11 UTC, tssweeney commented on .gitignore
> +cape_dev/
what is this?

2024-07-05 18:12 UTC, tssweeney commented on docs/docs/guides/integrations/cohere.md
> +---
@scottire may want to review docs as well

2024-07-05 18:17 UTC, tssweeney commented on weave/integrations/cohere/cohere_test.py
> +    assert output.text == exp
please also add assertions for: `started_at < ended_at`, `ended_at != None`, `exception == null`, and `op_name` are all correct. This comment applies to all tests

2024-07-05 18:19 UTC, tssweeney commented on weave/integrations/file::memory:?cache=shared
what is this??

2024-07-05 18:20 UTC, tssweeney requested changes
Looks really good!! (: Only a few comments to tend to

2024-07-12 17:54 UTC, tssweeney approved these changes

2024-07-12 18:01 UTC, merged