[WIP] docs(weave): Add new env vars catalog page under Tools
wandb/weave pull request #3036
Opened 2024-11-20 22:14 UTC by J2-D2-3PO

WIP DO NOT MERGE

## Description

Addresses https://wandb.atlassian.net/browse/DOCS-1053

Adds a new page summarizing and cataloging env vars under Tools

## Testing

TBD

2025-01-08 20:17 UTC, J2-D2-3PO commented on docs/docs/guides/tools/env-vars.md
> +| WF_CLICKHOUSE_HOST      | `localhost`                  | The host of the clickhouse server.                                                                |
@jamie-rasmussen not sure if I was understanding the CLICKHOUSE vars correctly, added default values based on https://github.com/wandb/weave/blob/master/weave/trace_server/environment.py

2025-01-08 20:57 UTC, jamie-rasmussen requested changes

2025-01-08 20:57 UTC, jamie-rasmussen commented on docs/docs/guides/tools/env-vars.md
> +| WF_CLICKHOUSE_HOST      | `localhost`                  | The host of the clickhouse server.                                                                |
I think `WF_CLICKHOUSE*` and `WF_TRACE_SERVER_URL` should not be in public documentation.

2025-01-08 20:57 UTC, jamie-rasmussen commented on docs/sidebars.ts
> +          items: ["guides/tools/serve", "guides/tools/deploy", "guides/tools/env-vars"],
This categorization doesn't seem right to me, these aren't a "tool" or "utility". I would put directly under Product Walkthrough or we could consider adding a category like "Reference"?

2025-01-08 20:57 UTC, jamie-rasmussen commented on docs/docs/guides/tools/env-vars.md
> +Here’s a complete list of available environment variables for Weave, along with their usage:
I'd probably not call it a complete list, there will be other internal ones.

2025-01-08 20:57 UTC, jamie-rasmussen commented on docs/docs/guides/tools/env-vars.md
> +| Variable Name            | Default Values                | Description                                                     |
I think it is confusing to call this column Default Values since it seems to suggest what would happen if the environment variable is not set. E.g. the default behavior when WEAVE_DEBUG_HTTP is unset is to not do the additional output logging. We should maybe just omit the column and explain the behavior for each in the description.

2025-01-08 20:57 UTC, jamie-rasmussen commented on docs/docs/guides/tools/env-vars.md
> +| WEAVE_PARALLELISM       | `20`                          | In evaluations, the number of examples to evaluate in parallel. `1` runs examples sequentially, while `0` will effectively execute all back
Where did this information about `0` come from? I don't think that's correct.

2025-01-09 00:04 UTC, J2-D2-3PO commented on docs/docs/guides/tools/env-vars.md
> +| WF_CLICKHOUSE_HOST      | `localhost`                  | The host of the clickhouse server.                                                                |
✅ Removed in https://github.com/wandb/weave/pull/3036/commits/427e2d3e7290e5bf558a5193e9e8d0a22b80e1a9

2025-01-09 00:06 UTC, J2-D2-3PO commented on docs/sidebars.ts
> +          items: ["guides/tools/serve", "guides/tools/deploy", "guides/tools/env-vars"],
I agree. In the current structure, it makes most sense to me to just put under Product Walkthrough. Updated in https://github.com/wandb/weave/pull/3036/commits/427e2d3e7290e5bf558a5193e9e8d0a22b80e1a9.

Overall, it would probably make more sense in a Reference section, but that gets into the docs structure refactor, which is a can of 🪱 s that we've not yet touched, so gonna punt that down the road

2025-01-09 00:07 UTC, J2-D2-3PO commented on docs/docs/guides/tools/env-vars.md
> +Here’s a complete list of available environment variables for Weave, along with their usage:
✅ Removed the word "complete" in https://github.com/wandb/weave/pull/3036/commits/427e2d3e7290e5bf558a5193e9e8d0a22b80e1a9

2025-01-09 00:07 UTC, J2-D2-3PO commented on docs/docs/guides/tools/env-vars.md
> +| Variable Name            | Default Values                | Description                                                     |
✅ Makes sense. Removed the "default" column in https://github.com/wandb/weave/pull/3036/commits/427e2d3e7290e5bf558a5193e9e8d0a22b80e1a9

2025-01-09 00:08 UTC, J2-D2-3PO commented on docs/docs/guides/tools/env-vars.md
> +| WEAVE_PARALLELISM       | `20`                          | In evaluations, the number of examples to evaluate in parallel. `1` runs examples sequentially, while `0` will effectively execute all back
✅ I was looking through the code and saw something about this, but I think I misunderstood. Removed in https://github.com/wandb/weave/pull/3036/commits/427e2d3e7290e5bf558a5193e9e8d0a22b80e1a9

2025-01-09 05:48 UTC, jamie-rasmussen approved these changes

2025-01-09 05:48 UTC, jamie-rasmussen commented on docs/docs/guides/core-types/env-vars.md
> +| WEAVE_PRINT_CALL_LINK   | Suppress the printing of call URLs. Default value is `false`.                            |
I'd say "if set to `false`." to match the first row.

2025-01-09 16:42 UTC, merged