docs(weave): Update platform doc with dedicated cloud info
wandb/weave pull request #3244
Opened 2024-12-13 22:35 UTC by J2-D2-3PO

https://wandb.atlassian.net/browse/DOCS-1119

Update https://weave-docs.wandb.ai/guides/platform/ with info about Dedicated Cloud based off of [Weave platform doc update - 12/2024](https://docs.google.com/document/d/181UEwLqTWU5Ivq9IIh0w4PL0fBVQjddCTUI8C1SGhsM/edit?tab=t.0}

2024-12-16 15:14 UTC, abhinavg6 requested changes
Thanks James. Requested a few changes here.

2024-12-16 15:14 UTC, abhinavg6 commented on docs/docs/guides/platform/index.md
> +  - **IP allowlisting:** Authorize access to your instance from specific IP addresses.
```suggestion
  - **[IP allowlisting](https://docs.wandb.ai/guides/hosting/data-security/ip-allowlisting):** Authorize access to your instance from specific IP addresses. This is an optional capability.
```

2024-12-16 15:14 UTC, abhinavg6 commented on docs/docs/guides/platform/index.md
> +  - **Private connectivity:** Route data securely through the cloud provider's private network.
```suggestion
  - **[Private connectivity](https://docs.wandb.ai/guides/hosting/data-security/private-connectivity):** Route data securely through the cloud provider's private network. This is an optional capability.
```

2024-12-16 15:14 UTC, abhinavg6 commented on docs/docs/guides/platform/index.md
> +  - **Data encryption:** Encrypt data at rest using a unique W&B-managed encryption key.
```suggestion
  - **[Data encryption](https://docs.wandb.ai/guides/hosting/data-security/data-encryption):** W&B encrypts data at rest using a unique W&B-managed encryption key.
```

2024-12-16 15:14 UTC, abhinavg6 commented on docs/docs/guides/platform/index.md
> +  - **Strong encryption mechanisms:** File-based encryption using Clickhouse Cloud's capabilities.
```suggestion
  - **Clickhouse cluster security:** W&B connects to the unique Clickhouse Cloud cluster for your Dedicated Cloud instance over the cloud provider's private network. W&B also encrypts the cluster using a unique W&B-managed encryption key, while leveraging Clickhouse's file level encryption.
```

2024-12-16 15:14 UTC, abhinavg6 commented on docs/docs/guides/platform/index.md
> +[The W&B Platform secure storage connector](https://docs.wandb.ai/guides/hosting/data-security/secure-storage-connector/?_gl=1*jzcfye*_gcl_au*OTI3ODM1OTcyLjE3MzE0MzU1NjUuMTYxOTQ4Mzk1LjE3MzMyNTYwMTYuM
```suggestion
[The W&B Platform secure storage connector or BYOB](https://docs.wandb.ai/guides/hosting/data-security/secure-storage-connector) is not available for Weave.
```

2024-12-16 16:15 UTC, abhinavg6 approved these changes
LGTM

2024-12-16 18:47 UTC, J2-D2-3PO commented
@scottire this is the PR I was referring to

2024-12-17 14:50 UTC, J2-D2-3PO commented
@wandb/weave-team can I get merge approval please?

2024-12-17 15:15 UTC, scottire approved these changes

2024-12-17 15:15 UTC, merged