feat: add artifact dependency ops
wandb/weave pull request #404
Opened 2023-08-18 18:38 UTC by jamie-rasmussen

Depends on https://github.com/wandb/core/pull/16594

Adds some ops for querying artifact dependencies.

2023-09-06 19:12 UTC, tssweeney commented on weave/ops_domain/artifact_version_ops.py
> +gql_direct_edge_op(
given the refactor of https://github.com/wandb/core/pull/16911, i think these need to be changed to `gql_connection_op(`

2023-09-06 19:13 UTC, tssweeney requested changes
See `gql_connection_op` comment

2023-09-06 19:19 UTC, jamie-rasmussen commented on weave/node_ref.py
> +        consistent (it does not allow deleting an artifact that has existing
I have a VS Code spellchecker extension that was recommended for use when editing our docs.
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

But mostly just noticing as I'm reading.

2023-09-14 14:38 UTC, tssweeney approved these changes

2023-09-14 14:38 UTC, merged